### ISSUE TITLE
problem with the Mix function on the standalone in Linux

### ISSUE THREAD

**Issue by tank-trax** [surge-synthesizer/surge-fx#17]
the Mix works properly with the VST but the Standalone goes from 100% to 58.5% to 41.5% to 0 without any gradients in between

Here are two examples. It occurs on all items that have the Mix knob.

![surge-fx mix 01](https://user-images.githubusercontent.com/41337033/62009681-13c90b00-b130-11e9-9ac3-51bbb816dbfe.gif)

![surge-fx mix 02](https://user-images.githubusercontent.com/41337033/62009682-16c3fb80-b130-11e9-9965-99dfb1df3d21.gif)

**Comment by baconpaul** [comment]
That reverb decay time TempoSync also looks wrong in 02. Must be my param sync mechanism falling over somehow. Thanks for the clear report

**Comment by baconpaul** [comment]
The "Decay Time Whole Note" is a problem with hangover of temposync. The mac doesn't show the quantized mix but does show that so will fix that first.

**Comment by baconpaul** [comment]
Fixed the temposync thing. Confirmed the mix is wonky on linux. Huh! Wonder why. Will look...
