### ISSUE TITLE
Surge-FX sometimes crashes when switching effects

### ISSUE THREAD

**Issue by mortfell** [surge-synthesizer/surge-fx#22]
I have experienced what appears to be a Windows only bug for Surge-FX.
**Platforms**
Have tested on REAPER, Ableton Live and FL-Studio.
Bug also effects the new 32 bit VST3 in REAPER 32-bit
I'm running Windows 10.

**BUG**
When switching between effects. Surge-fx often crashes.
No audio needs to be passing through, if you just randomly click through the effects it will happen eventually. It's possible the bug is exclusively related to switching to Frequency Shifter.

I tried to recreate with Mac and it didn't happen after a few minutes of changing effects so I think it's safe.

**GIF OF ME CAUSING A CRASH:**
![freqCrash](https://user-images.githubusercontent.com/4732794/64135739-40b4b180-cdb1-11e9-9df4-bc6818620dd3.gif)
You don't need to rapidly click through effects to get the bug, that is just a surefire way.

REAPER and Ableton Live hard crash. FL-Studio gave me this (hopefully) helpful error dialogue:
![freqCrashReadout](https://user-images.githubusercontent.com/4732794/64135761-9ab57700-cdb1-11e9-9afc-514aa7ba0311.jpg)

**Comment by mortfell** [comment]
Just did some more testing for a minute, definitely doesn't need to be the frequency shifter.

**Comment by baconpaul** [comment]
Thanks. On the vocoder issue, don found a crash also. I want to stress test this some and will stress test on windows also to look. There's some timing thing I'm missing in the plugin I need to fix before 1.6.2

**Comment by mortfell** [comment]
Ok great, let me know if there is anything else I should test.

**Comment by baconpaul** [comment]
Will do. I need a bit of dev time and to make it crash some so I can debug it. I'll update this issue and the vocoder issue when I have some changes in place.

**Comment by baconpaul** [comment]
OK so I just stressed the daylights out of it in logic and I can see a crash in the same spot that don did over on the surge proper vocoder issue.

```
Exception Codes:       KERN_INVALID_ADDRESS at 0x00000000000002e8
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Segmentation fault: 11
Termination Reason:    Namespace SIGNAL, Code 0xb
Terminating Process:   exc handler [11610]

VM Regions Near 0x2e8:
--> 
    __TEXT                 0000000109d3c000-000000010ba0a000 [ 28.8M] r-x/rwx SM=COW  /Applications/Logic Pro X.app/Contents/MacOS/Logic Pro X

Application Specific Information:
MALondonIII | e84d8ecce95d250e32c0f73d4c79d2b685e8718a80997af9a2b0f6c679216e01 | 28ef55f40e5dbf5cba062f4ca06868a3dc8a114d | 2019-07-04_15:24:24
 

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   com.SurgeSynthTeam.surgefx    	0x00000001246c4caa std::__1::__function::__func<SurgefxAudioProcessorEditor::SurgefxAudioProcessorEditor(SurgefxAudioProcessor&)::$_5, std::__1::allocator<SurgefxAudioProcessorEditor::SurgefxAudioProcessorEditor(SurgefxAudioProcessor&)::$_5>, void ()>::operator()() + 42
1   com.SurgeSynthTeam.surgefx    	0x00000001246b5eef SurgefxAudioProcessor::handleAsyncUpdate() + 31
2   com.SurgeSynthTeam.surgefx    	0x0000000124704327 juce::MessageQueue::runLoopSourceCallback(void*) + 55
3   com.apple.CoreFoundation      	0x00007fff3a511683 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
4   com.apple.CoreFoundation      	0x00007fff3a511629 __CFRunLoopDoSource0 + 108
5   com.apple.CoreFoundation      	0x00007fff3a4f4feb __CFRunLoopDoSources0 + 195
6   com.apple.CoreFoundation      	0x00007fff3a4f45b5 __CFRunLoopRun + 1189
7   com.apple.CoreFoundation      	0x00007fff3a4f3ebe CFRunLoopRunSpecific + 455
8   com.apple.HIToolbox           	0x00007fff397531ab RunCurrentEventLoopInMode + 292
9   com.apple.HIToolbox           	0x00007fff39752ded ReceiveNextEventCommon + 355
10  com.apple.HIToolbox           	0x00007fff39752c76 _BlockUntilNextEventMatchingListInModeWithFilter + 64
11  com.apple.AppKit              	0x00007fff37aeb79d _DPSNextEvent + 1135
12  com.apple.AppKit              	0x00007fff37aea48b -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1361
13  com.apple.logic10             	0x000000010b380c8a 0x109d3c000 + 23350410
14  com.apple.logic10             	0x000000010a9e4369 0x109d3c000 + 13271913
15  com.apple.logic10             	0x000000010a4623e2 0x109d3c000 + 7496674
16  com.apple.logic10             	0x000000010a47c6b8 0x109d3c000 + 7603896
17  com.apple.logic10             	0x000000010a6a607d 0x109d3c000 + 9871485
```

seems I am not properly timing my async conditions

It's hard to catch this on mac. I'll hop over to a windows VM now and give it a whirl too and also review the code carefully.

**Comment by baconpaul** [comment]
Ahh alright. Caught this in the debugger. The automation problem is a different one than the type switch problem.

Type switch problem is that when you switch types I delete the old effect instance (of course) but do that on a thread other than the audio thread (sigh) so we actually process a block in a deleted instance. Easy enough to fix I think!

**Comment by mortfell** [comment]
ok I think this is fixed! 
Just did a whole lotta clicking on windows 32bit and 64bit VST3
no crash

**Comment by baconpaul** [comment]
Yup awesome. Thanks for confirming!

It was a real bug. I was changing the pointer to the effect halfway through processing audio on the audio thread. Bad!
