### ISSUE TITLE
Distortion update to Surge-FX 

### ISSUE THREAD

**Issue by tank-trax** [surge-synthesizer/surge-fx#28]
Just a reminder to have this added to the Surge FX  

In TANH mode use TANH (#1244)
    
    I had left an if in from an early version which had 'none' in
    the mix of parameters; that de-facto meant that tanh mode
    (the default) had no waveshaper. Remove the specious if
    and restore the default behavior to the 1.6.2.1 behavior
    
    Addresess #1213

**Comment by baconpaul** [comment]
Thanks! Moved the pointer this morning.
