### ISSUE TITLE
Linux, VST3, Surge-FX does not save correct effect, cannot stream settings properly

### ISSUE THREAD

**Issue by tank-trax** [surge-synthesizer/surge-fx#33]
for the following, when a....

preset is saved as delay it opens as delay
preset is saved as reverb it opens as reverb
preset is saved as reverb2 it opens as chorus
preset is saved as phaser it opens as reverb2
preset is saved as flanger it opens as voco
preset is saved as rotary it opens as phaser
preset is saved as dist it opens as flanger
preset is saved as eq it opens as rotary
preset is saved as freq it opens as dist
preset is saved as cond it opens as eq
preset is saved as chorus it opens as freq
preset is saved as voco it opens as cond

**Comment by baconpaul** [comment]
ha well can you spot the off-by-one i must have made. Thanks I'll look at this this week and also upgrade the sub pointer.

**Comment by baconpaul** [comment]
This occurs when @VincyZed does it with a VST2 he built on linux
Does not do it standalone linux; nor with standalone nor au mac
Gonna upgrade to juce6 then look at linux vst3 to see if it happens there

**Comment by tank-trax** [comment]
I just built Surge-FX as a VST3 and it loads in Reaper
and the VST3 streams properly when reopening a saved preset

**Comment by baconpaul** [comment]
Great so I'm going to close this one then, since I'm just pushing the JUCE6 branch now.

**Comment by tank-trax** [comment]
it's recurring -> Items are moved over by two notches 
and SurgeEffectsBank is showing up as an Instrument in Reaper, Bitwig and Carla

cannot load old projects

will see if I can replicate what I did to get using JUCE6 for the VST3 that worked.   SurgeEffectsBank-linux-54e6661.tgz had the same result.

**Comment by baconpaul** [comment]
Can also pull a more recent juce into the project

**Comment by baconpaul** [comment]
Oh wow 

    IS_SYNTH TRUE

In the cmake file is why it is showing up as an instrument! Sorry that’s a bad copy from tws when I juce 6 ported

**Comment by tank-trax** [comment]
it seems like streaming is holding just that when FX is minimized and reopened the effect is notched over two spaces

when delay is selected and SurgeFX minimized and re-opened it displays as delay
when reverb is selected and SurgeFX minimized and re-opened it displays as reverb
when reverb2 is selected and SurgeFX minimized and re-opened it displays as reverb2
when phaser is selected and SurgeFX minimized and re-opened it displays as delay
when flanger is selected and SurgeFX minimized and re-opened it displays as voco
when rotary is selected and SurgeFX minimized and re-opened it displays as flanger
when eq is selected and SurgeFX minimized and re-opened it displays as rotary
when freq is selected and SurgeFX minimized and re-opened it displays as dist
when cond is selected and SurgeFX minimized and re-opened it displays as eq
when chorus is selected and SurgeFX minimized and re-opened it displays as freq
when delay is voco and SurgeFX minimized and re-opened it displays as cond

**Comment by tank-trax** [comment]
it's not streaming properly either

**Comment by baconpaul** [comment]
OK! I'll definitely take a look at all of that. Thank you.
