### ISSUE TITLE
Is there a way to use two of the Surge Effects Bank fx on one Cubase track? 

### ISSUE THREAD

**Issue by SimonDundas** [surge-synthesizer/surge-fx#42]
Is there a way to use two of the Surge Effects Bank fx on one Cubase track?    I'm trying to record automation of Freq and Distortion parameters but I think only one tab can be active at a time.  I tried 2 plugin instances on the track  but seemed to be the same.   Wonderful plugin.   Appreciate your advice.   Thanks

**Comment by baconpaul** [comment]
Hi!

I don't use cubase but I just tried an AU and VST3 host with the latest FX bank and it's no problem. 

Each instance of SFX runs one FX. Two instances run two. The screens look the same of course but they can be set individually.

And if you have two FX banks in your track you would need two windows.

So basically: Stack two plugins. In reaper it looked like "Instrument / Surge Effects / Surge effects" in my track.

**Comment by SimonDundas** [comment]
Thanks Paul.  I tried again and realised I'd bipassed one instance of the fx so it's now playing back both automation lanes.  Appreciate your help.

**Comment by baconpaul** [comment]
Great!
