### ISSUE TITLE
SurgeEffectsBank AU -Successfully validated but Version 'Invalid'

### ISSUE THREAD

**Issue by IPHOBBES** [surge-synthesizer/surge-fx#43]
HI ,

In Plugin manager of LPX SurgeEffectsBank AU -Successfully validated but Version 'Invalid'
Due to this behaviour effect bank works but upon Logic Pro startup it rescans  SurgeEffectsBank AU each time .
Ref Pic : https://pasteboard.co/Ka9sMwg.png
![Screenshot 2021-07-08 at 11 54 31 am](https://user-images.githubusercontent.com/76027905/124850360-d5a71800-dfe3-11eb-934f-06ecdb2431cb.png)

Surge 1.9.0 , macos 10.15.7 , Logic Pro 10.6.2

**Comment by baconpaul** [comment]
M1 or Intel?

**Comment by IPHOBBES** [comment]
Intel : Macbook pro 2012 , on Catalina

**Comment by baconpaul** [comment]
<img width="820" alt="Screen Shot 2021-07-09 at 8 50 14 AM" src="https://user-images.githubusercontent.com/13387561/125080381-bd420680-e092-11eb-8b17-fcba1bc37521.png">

OK I see the exact same thing (and moreover I see the same thing on our upcoming XT release also). I must have missed some JUCE configuration (In 1.9 SFXBank is JUCE but Surge is not; in XT everything is).

I might have a local patch to apply to the info.plist. Let me investigate and get back to you.

**Comment by IPHOBBES** [comment]
Thanks Paul , Yay that would be great , i have the same problem with one more plugin  ,  incase if you can tell me what exactly to change in the plist i could fix that plugin too :) all the best for your investigation.
