### ISSUE TITLE
Airwaves Losing FX Names in Logic

### ISSUE THREAD

**Issue by LogicallyEd** [surge-synthesizer/surge-fx#45]
Using standalone Surge FX plugin with Logic Pro X on Mac Ventura 13.2.1

Airwaves section is no longer displaying FX names (i.e. DeRez, Mojo, etc.)

It now only displays FX as a numeral  #1, thru #68

All dials are also generically listed as percentages.

Rescan an re-install doesn't fix. Neither does AU cache purge.

**Comment by baconpaul** [comment]
Ooof I haven’t tested anything on Ventura 

it’s just the airwindows? Chorus and delay and stuff are all fine? 

Also mind sharing the version of the fx plugin (which is displayed on the screen in the lower corner)

thanks for the report

**Comment by LogicallyEd** [comment]
Paul,

Yeah, I have sorta regretted updating to Ventura. I have some Brainworx plugins that got very buggy. They said they are working on it, but, we'll see. :-)

Anyway, version of Logic is 10.7.7
Version of Surge FX is 1.1.2.d3568a9

Appreciate you,
Ed

**Comment by baconpaul** [comment]
Thanks
A question - i wonder if there's a streaming issue. Old versions of the FX streamed the airwindows a bit oddly.

If you move the fx type knob a bit does the problem resolve?
Is it possible for you to share the "Air Amp Guitar Pedal" logic preset with me?

Disclosure - I won't be able to look for a few days at least so no rush.

**Comment by LogicallyEd** [comment]
Paul,

Changing the FX type knob just increases or lowers the number. I'll upload that preset in a bit.

I did notice after opening the Surge Synth, then going back to the FX only plugin, that the name under Airwindows FX had reset. I believe it came up as "Fire". But, closing the plugin window, then reopening, it was back to just the number. I couldn't find a combination of events that replicated this, though.

Again, appreciate your time. I'm enjoying many of the features and sounds in this standalone effects plugin!

Have a great day,
Ed

**Comment by LogicallyEd** [comment]
Here is the preset "Air Amp Guitar Pedal" by itself, and a second zip file with all of the presets I saved within the plugin. They rock, if I do say so myself. lol Maybe someone would find them useful.

Best,
Ed

[Air Amp Guitar Pedal.aupreset.zip](https://github.com/surge-synthesizer/surge-fx/files/11093265/Air.Amp.Guitar.Pedal.aupreset.zip)

[Eds_Surge_Presets.zip](https://github.com/surge-synthesizer/surge-fx/files/11093269/Eds_Surge_Presets.zip)

**Comment by LogicallyEd** [comment]
Aha. I had been loading the plugin on the Mix Bus, where it was blanking out the FX name as above.

However, after more experimenting, it seems that instances loaded to a track with audio (must in fact have audio)  then the FX window displays correctly.

Screenshot attached of the two instances of Surge-FX. On the left, it's on a track with audio, on the right, on the mix bus.

Lastly, it won't show up or load at all on a mono track. Track or bus has to be stereo.

<img width="1360" alt="Screenshot 2023-03-28 at 4 16 37 PM" src="https://user-images.githubusercontent.com/129200591/228357620-c436ec30-5c42-42c5-8c3d-c122af950072.png">

**Comment by baconpaul** [comment]
Oh @LogicallyEd I see you opened this in the FX repo. We should turn off issues in this repo! I've moved the conversation over to https://github.com/surge-synthesizer/surge/issues/6897 where I can reproduce the problem.

Basically: If the FX unit doesn't have an audio loop running then the airwindows display will be quite wrong.

**Comment by baconpaul** [comment]
Anyway I have a fix for this no-audio case which should be in the next nightly and in our 1.2 release in April. Thanks! I'll close this and we can move any followup over to the other issue.
